runtime: python39
instance_class: F4
entrypoint: streamlit run app.py --server.port=$PORT

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

env_variables:
  GOOGLE_API_KEY: "YOUR_API_KEY_HERE"

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
